#splits chartevents ids in x groups to be partitionned equaly
#@ahthor parisni
library(RPostgreSQL)

#
# Connect to the database
#
dbname <- "mimic"
user <- "postgres"
password <- gsub("^.*:","", scan("~/.pgpass",what="")[1])
host <- "localhost"
con <- dbConnect(dbDriver("PostgreSQL"), user=user,
		   password=password, dbname=dbname, host=host)
#
#
#

x <- dbGetQuery(con,"SELECT itemid FROM mimiciii.chartevents;")
dbDisconnect(con)

c <- table(x)
d <- c[as.character(sort(as.integer(names(c))))]
rm(c)
chunck <- function(x, n){
	file <- sprintf("chartevents_partitioned_%d.sql",n)
	l <- length(x)
	m <- sum(x) / n
	tmp <- 0
	mini <- names(x[1])
	ind = 0;
	create <- "-- Autogenerated with create_partitionning_chartevents.R\n-- CREATE CHARTEVENTS TABLE"
	trigg <- ""
	indexes <- ""
	for(i in 1:l){
		tmp = tmp +  x[i]
		if(tmp >= m){
			ind = ind + 1;
			print(sprintf("[%s-%s[",mini,names(x[i])))
		 	create = paste0( c(create,printChartevent(ind,mini,names(x[i]))),collapse="\n")
		 	trigg = paste0( c(trigg,printTriggerIn(ind,mini,names(x[i]))),collapse="\n")
		 	indexes = paste0( c(indexes,printIndexes(ind)),collapse="\n")
			mini <- (names(x[i]))
			tmp <- 0
		}
		if(i==l){
			ind = ind + 1;
			maxi <- as.character(as.integer(names(x[i])) +1)
			print(sprintf("[%s-%s[",mini,maxi))
		 	create = paste0( c(create,printChartevent(ind,mini,maxi)),collapse="\n")
		 	trigg = paste0( c(trigg,printTriggerIn(ind,mini,maxi)),collapse="\n")
		 	indexes = paste0( c(indexes,printIndexes(ind)),collapse="\n")
		}
	}
	cat(create,file=file)
	cat(printTrigger(trigg),file=file,append=T)
	cat(indexes,file=file,append=T)
}
printChartevent<- function(ind, mi, ma){
sprintf("CREATE TABLE chartevents_%d ( CHECK ( itemid >= %s  AND itemid < %s )) INHERITS (chartevents);",ind, mi, ma)
}

printTriggerIn <- function(ind, mi, ma){
if(ind==1){
	sprintf("IF ( NEW.itemid >= %s AND NEW.itemid < %s ) THEN INSERT INTO chartevents_%d VALUES (NEW.*);",mi,ma,ind)
}else{
	sprintf("ELSIF ( NEW.itemid >= %s AND NEW.itemid < %s ) THEN INSERT INTO chartevents_%d VALUES (NEW.*);", mi, ma, ind)
}
}

printTrigger <- function(str){
sprintf("
	
-- CREATE CHARTEVENTS TRIGGER
CREATE OR REPLACE FUNCTION chartevents_insert_trigger()
RETURNS TRIGGER AS $$
BEGIN

%s
	ELSE
RAISE EXCEPTION 'Itemid out of range.  Fix the chartevents_insert_trigger() function!';
       END IF;
RETURN NULL;
END;
$$
LANGUAGE plpgsql;

CREATE TRIGGER insert_chartevents_trigger
    BEFORE INSERT ON chartevents
    FOR EACH ROW EXECUTE PROCEDURE chartevents_insert_trigger();",str)
}

printIndexes <- function(ind){
sprintf("
---------------
-- CHARTEVENTS %d
---------------
drop index MIMICIII.CHARTEVENTS_%d_idx01;
CREATE INDEX CHARTEVENTS_%d_idx01 
  ON MIMICIII.CHARTEVENTS_%d (SUBJECT_ID, HADM_ID, ICUSTAY_ID) WITH (FILLFACTOR=100);


drop index MIMICIII.CHARTEVENTS_%d_idx02;
CREATE INDEX CHARTEVENTS_%d_idx02 
  ON MIMICIII.CHARTEVENTS_%d (ITEMID) WITH (FILLFACTOR=100);


drop index MIMICIII.CHARTEVENTS_%d_idx03;
CREATE INDEX CHARTEVENTS_%d_idx03 
  ON MIMICIII.CHARTEVENTS_%d (CHARTTIME, STORETIME) WITH (FILLFACTOR=100);


drop index MIMICIII.CHARTEVENTS_%d_idx04;
CREATE INDEX CHARTEVENTS_%d_idx04 
  ON MIMICIII.CHARTEVENTS_%d (CGID) WITH (FILLFACTOR=100);
",ind,ind,ind,ind,ind,ind,ind,ind,ind,ind,ind,ind,ind)
}

chunck(d, 100)
